<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

   <joint name="laser_joint" type="fixed">
     <parent link="base_link"/>
     <child link="laser_frame"/>
     <origin xyz="0.1 0 ${base_height + 0.02}" rpy="0 0 0"/>
   </joint>
   <link name="laser_frame">
      <visual>
         <origin xyz="0 0 0"/>
         <geometry>
            <cylinder length="0.04" radius="0.05"/>
         </geometry>
         <material name="laser_material">
            <color rgba="0.13 0.13 0.13 1.0"/>
         </material>
      </visual>
      <collision>
         <origin xyz="0 0 0"/>
         <geometry>
            <cylinder length="0.04" radius="0.05"/>
         </geometry>
      </collision>
      <xacro:cylinder_inertia m="0.1" r="0.05" l="0.04" o_xyz= "0 0 0" o_rpy= "0 0 0"/>
   </link>

   <!-- 2D Lidar New Gazebo Sensor Plugin  -->
   <gazebo reference="laser_frame">
      <sensor name="laser" type="gpu_lidar">
         <pose> 0 0 0 0 0 0 </pose>
         <always_on>true</always_on>
         <visualize>true</visualize>
         <update_rate>10</update_rate>
         <topic>scan</topic>
         <gz_frame_id>laser_frame</gz_frame_id>
         <lidar>
            <scan>
               <horizontal>
               <samples>360</samples>
               <min_angle>-3.14</min_angle>
               <max_angle>3.14</max_angle>
               </horizontal>
            </scan>
            <range>
               <min>0.3</min>
               <max>12</max>
            </range>
         </lidar>
      </sensor>
   </gazebo>
</robot>