<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

   <link name="laser_frame"/>

   <link name="mount_link">
      <visual>
         <geometry>
               <box size="0.035 0.0646 0.039" />
         </geometry>
         <origin xyz="0 0 0" rpy="0 0 0" />
         <material name="mycolor" />
      </visual>
      <collision>
         <geometry>
               <box size="0.035 0.0646 0.039" />
         </geometry>
         <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
      <xacro:box_inertia m="0.05" x="0.035" y="0.0646" z="0.039" o_xyz= "0 0 0.0195" o_rpy = "0 0 0"/>
      </link>

   <joint name="mount_joint" type="fixed">
      <parent link="base_link"/>
      <child link="mount_link"/>
      <origin xyz="0.015 -0.0067 ${base_height+0.0195}" rpy= "0 0 0"/>
   </joint>

   
   <link name="laser_link">
      <visual>
         <origin xyz="0 0 0"/>
         <geometry>
            <cylinder length="0.034" radius="${0.035/2}"/>
         </geometry>
         <material name="laser_material">
            <color rgba="0.13 0.13 0.13 1.0"/>
         </material>
      </visual>
      <collision>
         <origin xyz="0 0 0"/>
         <geometry>
            <cylinder length="0.034" radius="${0.035/2}"/>
         </geometry>
      </collision>
      <xacro:cylinder_inertia m="0.15" r="${0.035/2}" l="0.034" o_xyz= "0 0 0" o_rpy= "0 0 0"/>
   </link>

    <joint name="laser_joint" type="fixed">
     <parent link="mount_link"/>
     <child link="laser_link"/>
     <origin xyz="0 0 ${0.039/2 + 0.034/2}" rpy="0 0 0"/>
   </joint>


   <joint name="laser_frame_joint" type="fixed">
      <parent link="laser_link"/>
      <child link="laser_frame"/>
      <origin xyz="0 0 ${0.026-0.034/2}" rpy="0 0 ${3.14159265/2}"/>
   </joint>

   <gazebo reference = "laser_frame">
      <sensor name="imu_sensor" type="imu">
      <always_on>1</always_on>
      <update_rate>1</update_rate>
      <visualize>true</visualize>
      <topic>imu</topic>
   </sensor>

   </gazebo>
</robot>